### ISSUE TITLE
rustfmt

### ISSUE THREAD

**Issue by Euphrasiologist** [jtmccr1/fertree#2]
Hey JT, 

Do you think you could run rustfmt to format your code? I'm interested to read through some of it, and I think it would read nicer if formatted. I realise I could totally do this myself, but other people might be interested in this too!

https://github.com/rust-lang/rustfmt

I think you can just run:

`cargo fmt`

If you have it installed.

Cool work!
M

**Comment by jtmccr1** [comment]
done! good luck! I am sure there are better ways to appease the compiler in some places. I'd be happy to take any suggestions
